### ISSUE TITLE
Add subcommunities to backend/booklet

### ISSUE THREAD

**Issue by camtheman256** [mit-dormcon/t-rex#10]

**Comment by camtheman256** [comment]
Thinking about this one a little bit more and the purpose of REX is to have new frosh explore _dorms_ as opposed to individual living groups, so it could be worth looping back with @dtemkin1 @F1gN3wt0n on the ✨ philosophy ✨ of this feature.

**Comment by dtemkin1** [comment]
It might be good to show it on the event description on the website, but not too prominently? Maybe they can be shown similarly to how tags are displayed

**Comment by camtheman256** [comment]
> It might be good to show it on the event description on the website, but not too prominently? Maybe they can be shown similarly to how tags are displayed

Sounds good! Do you think this feature would be popular, and do you think there is enough time before this fall's REX to use it for this year?

**Comment by dtemkin1** [comment]
I don't know how useful it'll be, but hopefully we can collect data after REX and see if its a feature to keep around? We collected subcommunity data for everyone event. We'll be getting the list of approved events by July 31st, so if you think that's enough time, then let us know! 💃

**Comment by camtheman256** [comment]
Ok great! Yeah it’s plenty of time!

I just didn’t want to increase the complexity of everything if it wasn’t going to be useful.

**Comment by dtemkin1** [comment]
Sounds good! Keep us updated if you can 😌👍
